### PR TITLE
44 overview pages style

### PR DESCRIPTION
**Pull request by annikakrause**
Applied mock-up style to overview pages, set up for future styling is done. Colors are approved by POs.
Includes also #207.

RM: @annikakrause

### CODE REVIEW

**Review by steve-237 — COMMENTED** [review]
looks good !!

**Comment by steve-237** [comment]
Capture d’écran 2022-07-11 211005
Capture d’écran 2022-07-11 211152
These two icons are supposed to give details, why didn't you use the same icons?

**Comment by steve-237** [comment]
Capture
Capture2
The styles here are different it would have been better to have the same styles

**Review by steve-237 — APPROVED** [review]
Good job! Nice colors and icons, the software is prettier : )

**Comment by annikakrause** [comment]
> Capture d’écran 2022-07-11 211005 Capture d’écran 2022-07-11 211152 These two icons are supposed to give details, why didn't you use the same icons?

The description before was different, once "details" and once "expand". But after your issue #240, the functionality is equal, so you are right, I will have a look at it :)

**Pull request merged**
