### PR TITLE
style the pop up for the detail of a schema

### PR DESCRIPTION
**Pull request by steve-237**
Signed-off-by: steve-237 <steve0peg@gmail.com>

### CODE REVIEW

**Comment by annikakrause** [comment]
Why did you build a new component only for this schema pop-up? We have the information pop-up, which worked fine for more than one use case.

**Review by Idontker — CHANGES_REQUESTED** [review]
https://en.wikipedia.org/wiki/Polymorphism_(computer_science)

might use this to stop duplicating code

**Comment by steve-237** [comment]
> Why did you build a new component only for this schema pop-up? We have the information pop-up, which worked fine for more than one use case.
Capture d’écran 2022-07-23 230947

The component l created is supposed to be used for this issue but so far it has not been implemented yet. and that solves the problem with the view. The information pop up that I styled should be used to deliver error messages or success of operations as on the mockup. But if you have other modifications that you can make to improve the view please add them

**Comment by annikakrause** [comment]
> > Why did you build a new component only for this schema pop-up? We have the information pop-up, which worked fine for more than one use case.
> > Capture d’écran 2022-07-23 230947
> 
> The component l created is supposed to be used for this issue but so far it has not been implemented yet. and that solves the problem with the view. The information pop up that I styled should be used to deliver error messages or success of operations as on the mockup. But if you have other modifications that you can make to improve the view please add them

Yes, but we shouldn't duplicate code just for one use case. You could still use the information pop up and edit and extend it. There is always the possibility to use "ngIf" in html, if that helps you.

**Comment by Idontker** [comment]
> > Why did you build a new component only for this schema pop-up? We have the information pop-up, which worked fine for more than one use case.
> > Capture d’écran 2022-07-23 230947
> 
> The component l created is supposed to be used for this issue but so far it has not been implemented yet. and that solves the problem with the view. The information pop up that I styled should be used to deliver error messages or success of operations as on the mockup. But if you have other modifications that you can make to improve the view please add them

You are right. We have a lot of smaller dialogs which could be refactored if needed in the future. Although I do not like the it, i can stay for now.

**Review by Idontker — APPROVED** [review]

**Comment by steve-237** [comment]
Capture d’écran 2022-07-24 125224

There is a small problem at this level, we cannot fully read what is written on the image. Is it supposed to be like this?

**Pull request merged**
