### PR TITLE
169 overview of proof templates

### PR DESCRIPTION
**Pull request by annikakrause**
Finished functionalities of #169 (overview page works, frontend and backend are done).
Tests are missing so far.

RM: @valentinBraeutigam

### CODE REVIEW

**Review by Jean28518 — CHANGES_REQUESTED** [review]
Looks good!
Please add tests for the LissiApiService and the TemplateProofController.
I would wait until Karol merged his urgent PR, then start working on this.

**Comment by annikakrause** [comment]
We will edit our backend changes after Karols urgent PR and ask for your review again :)

Tests will be added later in a new pull request, that doesn't belong to this one

**Comment by valentinBraeutigam** [comment]
added tests to Component :)

**Review by Jean28518 — CHANGES_REQUESTED** [review]
I can't see any tests in my review and neither in the branch repository.. 
Maybe they got deleted by the pull from the main?

**Comment by valentinBraeutigam** [comment]
> I can't see any tests in my review and neither in the branch repository.. Maybe they got deleted by the pull from the main?

For me both contain the tests. So I'm a little bit confused.

**Review by Jean28518 — APPROVED** [review]
Looks good! Can be merged now :)

**Pull request merged**
