### PR TITLE
265 landing page style

### PR DESCRIPTION
**Pull request by jackDS008**

### CODE REVIEW

**Comment by steve-237** [comment]
Capture d’écran 2022-07-18 204958
Should be great if the cards are on the same line
Capture d’écran 2022-07-18 205105
 and the style a bit adjusted

**Comment by jackDS008** [comment]
I adjusted the size a little bit and changed the <h2> to a <h3>, so that it can be used on smaller devices.

For the style I used the original icons of lissi. I tried it with the blue on the bottom and it didn't look as good as now.

**Comment by jackDS008** [comment]
Please review again @steve-237

**Review by steve-237 — APPROVED** [review]

**Comment by annikakrause** [comment]
> image Looks better now ! But it looks like the cards are not aligned. I don't know if my browser is doing this. How is that on your side please?

I get the same problem as soon as I decrease the size of the window. Also the icons are not aligned in the center of the card @jackDS008.

**Pull request merged**
