### PR TITLE
Fixed login enter bug

### PR DESCRIPTION
**Pull request by valentinBraeutigam**
fixes weird behavior on the password pages. Before when pressing enter the hide button was activated and when activating the hide button twice the login/change password method was called.

### CODE REVIEW

**Review by steve-237 — COMMENTED** [review]
Works good ! But when l'm in the last text field and l press enter the cursor goes back to the text field "enter your old password".

**Comment by steve-237** [comment]
> Works good ! But when l'm in the last text field and l press enter the cursor goes back to the text field "enter your old password".

On the change password page

**Comment by valentinBraeutigam** [comment]
First of all the change password function is called when enter is pressed. Also I think that this behavior is better since either the password or the email was wrong. So you want to change either the password or the email and in most cases the password is wrong.

**Comment by steve-237** [comment]
> First of all the change password function is called when enter is pressed. Also I think that this behavior is better since either the password or the email was wrong. So you want to change either the password or the email and in most cases the password is wrong.

Okay! In this case everything is fine.

**Review by steve-237 — APPROVED** [review]

**Pull request merged**
