### PR TITLE
Display error messages in registration process

### PR DESCRIPTION
**Pull request by Jean28518**
Implements #101 completely.

Signed-off-by: Jean-Frédéric Vogelbacher <jean-frederic.vog.vogelbacher@fau.de>

### CODE REVIEW

**Review by Idontker — CHANGES_REQUESTED** [review]
The error function (l.131 and following) is only called if an error in the fronted occurs (e.g. could not parse response to given format).
A correct response with an error code should be displayed in l. 124 and following.

**Comment by Idontker** [comment]
Mh, maybe the behavior when reciving 4xx and 5xx differs. I tested only 4xx codes when implementing my feature this week. @valentinBraeutigam, can you help us.

**Comment by valentinBraeutigam** [comment]
Maybe you can tell me how you get the error? I tried it without having my email credentials set in the backend and I got a 500 back with a message that it is a 400 :)

**Comment by Jean28518** [comment]
It's a 500 error for us, because the client gets an 400 error while calling the Lissi API

**Review by annikakrause — APPROVED** [review]

**Pull request merged**
