### PR TITLE
293 encryption

### PR DESCRIPTION
**Pull request by jackDS008**

### CODE REVIEW

**Review by valentinBraeutigam — CHANGES_REQUESTED** [review]
It seems to work, but you have to support the change password for not encrypted password. For now it just fails because it tries to decode them (for the case that sending a mail fails). 

Maybe you can check if it's in the right format before or just don't decode (because I think the only thing you do with it is to encrypt it again and set it as password again). Another alternative would be to just save the user if sending the mail was successful (You would have to do nothing with the old password)

Edit: I meant the forgot password method ^^

**Comment by jackDS008** [comment]
done, please review again

**Review by valentinBraeutigam — COMMENTED** [review]
Looks good now. It can be approved after adjusting the backend tests
grafik

**Comment by jackDS008** [comment]
@valentinBraeutigam I adjusted the tests, please review again

**Review by valentinBraeutigam — APPROVED** [review]

**Pull request merged**
