### PR TITLE
129 prefilled password change

### PR DESCRIPTION
**Pull request by Idontker**
PM: @valentinBraeutigam

### CODE REVIEW

**Comment by Idontker** [comment]
reviewer might tell me whether I should create automatic tests for these lines of code. IMO: all I do is calling the API :)

**Review by annikakrause — CHANGES_REQUESTED** [review]
- [x] please mind spelling errors, if we approve them, it's harder to fix them later (e.g. "changePasswordPrefiled" vs. "changePasswordPrefilled", "Sie" with capital letters in the email...)
- [ ] the link itself doesn't work for now, it links to the device name without any port instead of "localhost:4200"
- [ ] prefill of the password fails when using some specific symbols like ". Example: Passwort:`§9@7w{Hd80Wul^~"?3y1` -> prefilled part: `§9@7w{Hd80Wul^~`

**Comment by Idontker** [comment]
> * [ ]  please mind spelling errors, if we approve them, it's harder to fix them later (e.g. "changePasswordPrefiled" vs. "changePasswordPrefilled", "Sie" with capital letters in the email...)

Spelling errors are an easy refactoring. Most IDEs support a quick and easy renaming.

**Comment by Idontker** [comment]
> * [ ]  prefill of the password fails when using some specific symbols like ". Example: Passwort:`§9@7w{Hd80Wul^~"?3y1` -> prefilled part: `§9@7w{Hd80Wul^~`

True. I think a similar issue lies within the HttpBackendService of the frontend. As we  send all parameters within the URL / URI certain special characters will result in unwanted behavior. This will happen in login and change password 

I will fix the strong password now, but we might need to check whether this issue will occur within the login/change password process

**Comment by Idontker** [comment]
> * [ ]  the link itself doesn't work for now, it links to the device name without any port instead of "localhost:4200"

I do not encounter this issue :| 
The url is pulled from the application .properties ``frontend.host.url.change.password``

Are you sure that you ve set them up correctly? I used: 
```
frontend.host.url.change.password=http://localhost:4200/password/change
```

**Comment by annikakrause** [comment]
> > * [ ]   please mind spelling errors, if we approve them, it's harder to fix them later (e.g. "changePasswordPrefiled" vs. "changePasswordPrefilled", "Sie" with capital letters in the email...)
> 
> Spelling errors are an easy refactoring. Most IDEs support a quick and easy renaming.

Of course, but normally there should be no need for such refactoring ;)

**Comment by annikakrause** [comment]
> > * [ ]   the link itself doesn't work for now, it links to the device name without any port instead of "localhost:4200"
> 
> I do not encounter this issue :| The url is pulled from the application .properties `frontend.host.url.change.password`
> 
> Are you sure that you ve set them up correctly? I used:
> 
> ```
> frontend.host.url.change.password=http://localhost:4200/password/change
> ```

You are right, I forgot to change this after Jean's Docker changes, thanks!

**Review by annikakrause — APPROVED** [review]

**Pull request merged**
