### PR TITLE
Disabled button #257

### PR DESCRIPTION
**Pull request by jackDS008**
Signed-off-by: Jannik Kiesel <jannik.kiesel@fau.de>

### CODE REVIEW

**Review by steve-237 — CHANGES_REQUESTED** [review]
Great Job! 

It's missing a disabled image selection  button on the create schema page.
The buttons on the other pages are indeed deactivated and we have the warning message

**Comment by jackDS008** [comment]
Good point, I added it to the create schema page

**Review by steve-237 — CHANGES_REQUESTED** [review]
image

warning messages are not appropriate for the pages on which they are displayed

**Comment by steve-237** [comment]
It is the same for the other page.

**Comment by jackDS008** [comment]
Resolved and done the naming, thanks for the review

**Review by steve-237 — APPROVED** [review]

**Pull request merged**
